import 'package:flutter/material.dart';

import '../core/theme/forge_theme.dart';
import '../json_ui/renderer/forge_renderer.dart';

/// FORGE v0.2 P5対応(指示書19章「Generated by Forge」)。
///
/// 生成されたアプリを開いた際、邪魔にならない小さな`Generated by Forge`
/// 表示を、Runtime文書の内部(偽Widgetとして)ではなく、Host側の薄い
/// Shellとして重ねる。アプリ本体の操作は一切妨げない
/// (`IgnorePointer`は使わず、ラベル自体が画面下部の狭い帯に収まるのみ)。
class GeneratedAppHostShell extends StatelessWidget {
  final Map<String, dynamic> forgeDocument;
  final VoidCallback? onBack;

  const GeneratedAppHostShell({super.key, required this.forgeDocument, this.onBack});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(child: ForgeDocumentView(rawJson: forgeDocument)),
        if (onBack != null)
          Positioned(
            top: MediaQuery.of(context).padding.top + 8,
            left: 8,
            child: _RoundIconButton(icon: Icons.arrow_back_rounded, onPressed: onBack!),
          ),
        Positioned(
          bottom: 10,
          left: 0,
          right: 0,
          child: IgnorePointer(
            child: Center(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: ForgeTheme.ink.withValues(alpha: 0.55),
                  borderRadius: BorderRadius.circular(999),
                ),
                child: const Text(
                  'Generated by Forge',
                  style: TextStyle(fontSize: 10, color: Colors.white, fontWeight: FontWeight.w500),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _RoundIconButton extends StatelessWidget {
  final IconData icon;
  final VoidCallback onPressed;
  const _RoundIconButton({required this.icon, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: ForgeTheme.surface.withValues(alpha: 0.92),
      shape: const CircleBorder(),
      elevation: 1,
      child: IconButton(
        icon: Icon(icon, color: ForgeTheme.ink),
        tooltip: '戻る',
        onPressed: onPressed,
      ),
    );
  }
}
