import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../core/theme/forge_theme.dart';
import '../core/di/network_providers.dart';
import '../features/app_generation/domain/entities/generation_outcome.dart';
import '../features/app_generation/presentation/screens/conversation_flow_screen.dart';
import '../json_ui/renderer/forge_renderer.dart';
import 'ai_mode.dart';

/// FORGE v0.2 P5対応(指示書19章「Generated by Forge」)。
///
/// 生成されたアプリを開いた際、邪魔にならない小さな`Generated by Forge`
/// 表示を、Runtime文書の内部(偽Widgetとして)ではなく、Host側の薄い
/// Shellとして重ねる。アプリ本体の操作は一切妨げない
/// (`IgnorePointer`は使わず、ラベル自体が画面下部の狭い帯に収まるのみ)。
///
/// FORGE-PRODUCT-VISION-002(2026-08-11)対応: `onDocumentUpdated`を
/// 渡した呼び出し元でのみ、「ここを変える」ボタンが現れる(Held→
/// Forming→Heldの入口、design doc C章)。`StatelessWidget`から
/// `StatefulWidget`へ変更したのは、更新後のDocumentをこのWidget自身が
/// 保持し、`ForgeDocumentView`を新しい内容で再描画するため
/// (呼び出し元は「保存してほしい」という通知だけを`onDocumentUpdated`
/// 経由で受け取り、実際の永続化方法は呼び出し元が決める——My Apps
/// 画面・履歴画面等、保存先を持たない画面は単にこの引数を渡さなければ
/// よく、影響を受けない)。
class GeneratedAppHostShell extends ConsumerStatefulWidget {
  final Map<String, dynamic> forgeDocument;
  final VoidCallback? onBack;

  /// FORGE-AI-QUALITY-001(2026-08-11)新設(ローカル永続化対応)。
  /// 画面ID→前回保存された実行時State。呼び出し元(`AppLibraryRepository`
  /// 経由でローカルストレージから読み込む My Apps・履歴・ホーム画面の
  /// 各画面)が渡す。生成直後でまだ保存されていないプレビュー
  /// (`generation_flow_screen.dart`)からは渡されず、その場合は
  /// 常に文書の初期値のまま(既存の挙動を保つ)。
  final Map<String, Map<String, dynamic>>? initialRuntimeState;

  /// FORGE-AI-QUALITY-001(2026-08-11)新設。渡した場合のみ、実際に
  /// アプリの状態変化がローカルストレージへ保存される(呼び出し元が
  /// 保存先を持たない場合は渡さないだけでよい、既定`null`で無効)。
  final void Function(String screenId, Map<String, dynamic> stateJson)? onScreenStateChanged;

  /// FORGE-PRODUCT-VISION-002(2026-08-11)新設。非nullの場合のみ、
  /// 「ここを変える」ボタンを表示する。`ConversationFlowScreen`が
  /// `/converse`経由でUPDATE(TD40)に成功すると、更新済みのDocumentを
  /// 持ってこのコールバックが呼ばれる(呼び出し元は永続化するかどうかを
  /// 自由に決めてよい)。
  final void Function(Map<String, dynamic> updatedDocument)? onDocumentUpdated;

  /// 会話に使うAI Provider(Home画面のトグルと同じ値、既定`null`=Backend既定)。
  final String? provider;

  /// FORGE-HANDOFF-LOCAL-AI-UX-004 §9(2026-08-13)新設。このToolが
  /// Mockの模擬出力から作られたかどうか。`true`のとき、下部の
  /// 「Generated by Forge」バッジを、模擬であることを明示する文言へ
  /// 差し替える(指示書:「Silent Mock fallbackは禁止」——Mock由来の
  /// Toolを本物として黙って見せない)。
  ///
  /// 既定`false`のため、既存の呼び出し元(My Apps・履歴など、保存済み
  /// Toolを開く画面)の見た目は一切変わらない。
  final bool simulated;
  final ArtifactIdentity? artifact;

  const GeneratedAppHostShell({
    super.key,
    required this.forgeDocument,
    this.onBack,
    this.initialRuntimeState,
    this.onScreenStateChanged,
    this.onDocumentUpdated,
    this.provider,
    this.simulated = false,
    this.artifact,
  });

  @override
  ConsumerState<GeneratedAppHostShell> createState() => _GeneratedAppHostShellState();
}

class _GeneratedAppHostShellState extends ConsumerState<GeneratedAppHostShell> {
  late Map<String, dynamic> _document = widget.forgeDocument;
  late ArtifactIdentity? _artifact = widget.artifact;
  bool _submittingSignal = false;

  /// 送信中の「これでOK」に割り当てた冪等キー（FORGE-019A §8）。
  ///
  /// **同じ操作の再送では同じキーを使い、成功したら捨てる。**
  ///
  /// 019は`DateTime.now().microsecondsSinceEpoch`を毎回作っていたので、
  /// **再送のたびに別のキー**になっていた。冪等キーの目的は「同じ操作が
  /// 二度届いたことをサーバが見分けられるようにする」ことなので、
  /// 毎回変えるのは意味が正反対である。通信が不安定なだけで、評価が
  /// 何件も積まれる。
  ///
  /// 成功したら`null`へ戻す。あとで利用者がもう一度評価したときは、
  /// **それは別の操作**なので新しいキーになる（017A §2で、時系列は
  /// 事実として残るようにしてある）。
  String? _pendingAcceptKey;

  /// 送信中の修正要求に割り当てた冪等キーと、その要求文。
  ///
  /// 要求文が変われば**別の操作**なのでキーも変える。
  String? _pendingRevisionKey;
  String? _pendingRevisionRequest;

  int _actionSequence = 0;

  String _newIdempotencyKey(String prefix) {
    _actionSequence += 1;
    return '$prefix-${DateTime.now().microsecondsSinceEpoch}-$_actionSequence';
  }

  Future<void> _accept() async {
    final artifact = _artifact;
    if (artifact == null || _submittingSignal) return;
    // 失敗して押し直した場合は**同じキー**を使う。成功後にだけ捨てる。
    final idempotencyKey = _pendingAcceptKey ??= _newIdempotencyKey('flutter-accepted');
    setState(() => _submittingSignal = true);
    try {
      await ref.read(dioClientProvider).post<Map<String, dynamic>>('/api/v1/ai/feedback', data: {
        'signal': 'accepted',
        'artifact_id': artifact.artifactId,
        'seen_version_token': artifact.versionToken,
        'idempotency_key': idempotencyKey,
      });
      _pendingAcceptKey = null;
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('フィードバックを記録しました')));
    } finally {
      if (mounted) setState(() => _submittingSignal = false);
    }
  }

  Future<void> _requestRevision() async {
    final artifact = _artifact;
    if (artifact == null || _submittingSignal) return;
    final controller = TextEditingController();
    final request = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('どこを直しますか？'),
        content: TextField(controller: controller, autofocus: true,
          decoration: const InputDecoration(hintText: '例: 残高をもっと目立たせて')),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('キャンセル')),
          FilledButton(onPressed: () => Navigator.pop(context, controller.text.trim()), child: const Text('修正する')),
        ],
      ),
    );
    controller.dispose();
    if (request == null || request.isEmpty || !mounted) return;
    // 同じ要求文の再送は同じ操作。文が違えば別の操作である（§8）。
    if (_pendingRevisionKey == null || _pendingRevisionRequest != request) {
      _pendingRevisionKey = _newIdempotencyKey('flutter-correction');
      _pendingRevisionRequest = request;
    }
    final idempotencyKey = _pendingRevisionKey!;
    setState(() => _submittingSignal = true);
    try {
      final response = await ref.read(dioClientProvider).post<Map<String, dynamic>>('/api/v1/ai/update', data: {
        'forge_document': _document,
        'change_request': request,
        'artifact_id': artifact.artifactId,
        'seen_version_token': artifact.versionToken,
        'idempotency_key': idempotencyKey,
      });
      final result = response.data?['result'] as Map<String, dynamic>?;
      final updated = result?['forge_document'] as Map<String, dynamic>?;
      final identity = result?['artifact'] as Map<String, dynamic>?;
      if (updated == null || identity == null) throw StateError('invalid revision response');
      // 成功したので、この操作のキーは役目を終えた。次の修正は別の操作。
      _pendingRevisionKey = null;
      _pendingRevisionRequest = null;
      if (!mounted) return;
      setState(() {
        _document = updated;
        // **新しい版のcapabilityへ差し替える。**
        //
        // ここを忘れると、利用者が続けて直そうとしたときに古い
        // version_tokenを送ることになり、必ず`stale_artifact`で弾かれる
        // ——「一度直したら二度目が通らない」という形で壊れる。
        _artifact = ArtifactIdentity(
          artifactId: identity['artifact_id'] as String,
          versionToken: identity['version_token'] as String,
        );
      });
      widget.onDocumentUpdated?.call(updated);
    } finally {
      if (mounted) setState(() => _submittingSignal = false);
    }
  }

  Future<void> _openEditConversation() async {
    final updated = await Navigator.of(context).push<Map<String, dynamic>>(
      MaterialPageRoute<Map<String, dynamic>>(
        builder: (_) => ConversationFlowScreen(
          provider: widget.provider, currentDocument: _document,
        ),
      ),
    );
    if (updated == null || !mounted) return;
    setState(() => _document = updated);
    widget.onDocumentUpdated?.call(updated);
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(child: ForgeDocumentView(
          rawJson: _document,
          initialRuntimeState: widget.initialRuntimeState,
          onScreenStateChanged: widget.onScreenStateChanged,
        )),
        if (widget.onBack != null)
          Positioned(
            top: MediaQuery.of(context).padding.top + 8,
            left: 8,
            child: _RoundIconButton(icon: Icons.arrow_back_rounded, onPressed: widget.onBack!),
          ),
        if (widget.onDocumentUpdated != null)
          Positioned(
            top: MediaQuery.of(context).padding.top + 8,
            right: 8,
            child: _RoundIconButton(icon: Icons.chat_bubble_outline_rounded, onPressed: _openEditConversation),
          ),
        if (_artifact != null)
          Positioned(
            bottom: 42,
            left: 16,
            right: 16,
            child: SafeArea(
              top: false,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  FilledButton.icon(
                    key: const Key('forge_feedback_accepted'),
                    onPressed: _submittingSignal ? null : _accept,
                    icon: const Icon(Icons.check_rounded),
                    label: const Text('これでOK'),
                  ),
                  const SizedBox(width: 8),
                  OutlinedButton.icon(
                    key: const Key('forge_feedback_revise'),
                    onPressed: _submittingSignal ? null : _requestRevision,
                    icon: const Icon(Icons.tune_rounded),
                    label: const Text('直したい'),
                  ),
                ],
              ),
            ),
          ),
        Positioned(
          bottom: 10,
          left: 0,
          right: 0,
          child: IgnorePointer(
            child: Center(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: ForgeTheme.ink.withValues(alpha: 0.55),
                  borderRadius: BorderRadius.circular(999),
                ),
                child: Text(
                  // **呼び出し側の渡し忘れで「本物」に見せない。**
                  // `simulated` の既定値は `false` なので、渡し忘れると
                  // 疑似データが `Generated by Forge` と名乗ってしまう。
                  // ビルド自体が疑似モードかどうかを、ここで必ず足す
                  // （`isSimulatedOutput`、2026-09-02 実機描画で発見）。
                  isSimulatedOutput(backendSaidSimulated: widget.simulated)
                      ? 'お試し用の疑似データ(AI未接続)'
                      : 'Generated by Forge',
                  style: const TextStyle(fontSize: 10, color: Colors.white, fontWeight: FontWeight.w500),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class _RoundIconButton extends StatelessWidget {
  final IconData icon;
  final VoidCallback onPressed;
  const _RoundIconButton({required this.icon, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: ForgeTheme.surface.withValues(alpha: 0.92),
      shape: const CircleBorder(),
      elevation: 1,
      child: IconButton(
        icon: Icon(icon, color: ForgeTheme.ink),
        tooltip: '戻る',
        onPressed: onPressed,
      ),
    );
  }
}
